### ISSUE TITLE
Not working on HavocOS

### ISSUE THREAD

**Issue by crashoverride1995** [Magisk-Modules-Repo/op3slowmofix#1]
The service.sh file is empty and doesn't contain the necessary code which the original module has in order to work properly. If you need help, feel free to contact me.

**Comment by MarcAnt01** [comment]
Hello, I have just realized I have forgotten not to replace the service.sh file while updating to the new template, will deliver the fix along with device check fix for OOS. If you prefer, you can embark a pr and I will merge it. Thanks for making me notice 😀
